'use client'

import { useEffect, useState } from 'react'
import { motion, useScroll, useSpring, useTransform } from 'framer-motion'
import { ArrowUpRight, BadgeCheck, BookOpen, Check, ChevronDown, Code2, Cpu, Download, ExternalLink, GraduationCap, Layers3, Mail, Menu, Network, Radio, ScanLine, Server, ShieldCheck, Sparkles, Terminal, Trophy, X, Zap } from 'lucide-react'

const sections = ['About', 'Skills', 'Projects', 'Achievements', 'Certifications', 'Education', 'Contact']
const skills = { 'Programming Languages': ['C++', 'JavaScript', 'C', 'Python'], 'Frameworks / Technologies': ['HTML', 'CSS', 'Arduino Framework'], 'Tools & Platforms': ['MySQL', 'AutoCAD', 'Cisco Packet Tracer', 'VirtualBox', 'Canva'], 'Soft Skills': ['Problem Solving', 'Communication', 'Leadership', 'Adaptability', 'Teamwork'] }
const education = [
  ['Since August 2025', 'Lovely Professional University', 'Bachelor of Technology — Computer Science and Engineering', 'CGPA: 7.00'],
  ['April 2022 — March 2024', 'Universal Public School, Deoria, Uttar Pradesh', 'Intermediate', 'Percentage: 65%'],
  ['April 2020 — March 2022', 'Little Flower School, Deoria, Uttar Pradesh', 'Matriculation', 'Percentage: 80%'],
]
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: .6, ease: 'easeOut' } } }

function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) {
  return <motion.section id={id} className="section-shell" variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }}><div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</motion.section>
}

export default function Portfolio() {
  const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); const [active, setActive] = useState('About')
  const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 100, damping: 30 }); const width = useTransform(progress, [0, 1], ['0%', '100%'])
  useEffect(() => { const onScroll = () => { setScrolled(window.scrollY > 24); const current = sections.find((id) => { const el = document.getElementById(id); return el && window.scrollY >= el.offsetTop - 180 }) || 'About'; setActive(current) }; window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <main className="site-shell">
    <motion.div className="scroll-progress" style={{ width }} />
    <nav className={`nav ${scrolled ? 'nav-scrolled' : ''}`} aria-label="Primary navigation"><a className="brand" href="#top"><span className="brand-mark">SK</span><span>Sushil Kumar Rai</span></a><div className="desktop-nav">{sections.map(s => <a className={active === s ? 'active' : ''} href={`#${s}`} key={s}>{s}</a>)}</div><button className="menu-button" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu}>{menu ? <X /> : <Menu />}</button></nav>
    {menu && <motion.div className="mobile-nav" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>{sections.map(s => <a href={`#${s}`} onClick={() => setMenu(false)} key={s}>{s}</a>)}</motion.div>}
    <header id="top" className="hero"><div className="hero-copy"><div className="status"><span className="status-dot" /> Open to learning and building</div><p className="kicker">B.Tech CSE Student <span>/</span> Developer <span>/</span> IoT Enthusiast</p><h1>Building <em>ideas</em><br />into reality.</h1><p className="hero-text">I&apos;m Sushil, a Computer Science and Engineering student interested in programming, software development, IoT, and solving meaningful problems through technology.</p><div className="hero-actions"><a className="button button-primary" href="#Projects">View my projects <ArrowUpRight size={16} /></a><a className="button button-ghost" href="/resume/sushil-kumar-rai-cv.pdf" download>Download resume <Download size={16} /></a></div><div className="social-row"><a href="https://github.com/sushil7255" target="_blank" rel="noreferrer"><Code2 size={17} /> GitHub</a><a href="https://linkedin.com/in/sushilkumarrai7255" target="_blank" rel="noreferrer"><Network size={17} /> LinkedIn</a><a href="mailto:sushilkumarrai7255@gmail.com"><Mail size={17} /> Email</a></div></div><div className="terminal-card"><div className="terminal-top"><span><i /><i /><i /></span><small>iot-vehicle-security.ts</small><Code2 size={15} /></div><div className="terminal-body"><p><b className="pink">const</b> vehicle = <b className="blue">new</b> <b className="green">SecuritySystem</b>({'{'}</p><p className="indent"><span className="muted">access</span>: [<span className="orange">&apos;RFID&apos;</span>, <span className="orange">&apos;fingerprint&apos;</span>],</p><p className="indent"><span className="muted">controller</span>: <span className="orange">&apos;ESP32&apos;</span>,</p><p className="indent"><span className="muted">connected</span>: <span className="blue">true</span>,</p><p>{'}'});</p><br /><p><span className="green">&gt;</span> system.status()</p><p className="output"><Check size={14} /> access control ready</p><p className="output"><Check size={14} /> wifi connection active</p><p className="cursor">_</p></div><div className="terminal-footer"><span><Radio size={14} /> live system</span><span>ESP32 · Wi-Fi</span></div></div></header>
    <Section id="About" eyebrow="01 / About" title="A student with a builder's mindset."><div className="about-grid"><p className="lead">I&apos;m currently pursuing my Bachelor of Technology in Computer Science and Engineering at Lovely Professional University. I enjoy turning ideas into working systems and continuously learning new technologies along the way.</p><div className="about-note"><Sparkles size={20} /><p>Interested in programming, software development, IoT, problem solving, and growing through practical work.</p></div></div></Section>
    <Section id="Skills" eyebrow="02 / Toolkit" title="Tools I use to make things work."><div className="skills-grid">{Object.entries(skills).map(([group, items], i) => <motion.div className="skill-group" key={group} whileHover={{ y: -4 }}><div className="skill-icon">{i === 0 ? <Code2 /> : i === 1 ? <Layers3 /> : i === 2 ? <Terminal /> : <Network />}</div><h3>{group}</h3><div className="tag-list">{items.map(item => <span key={item}>{item}</span>)}</div></motion.div>)}</div></Section>
    <Section id="Projects" eyebrow="03 / Selected work" title="From idea to working system."><motion.article className="featured-project" whileInView={{ opacity: 1, y: 0 }} initial={{ opacity: 0, y: 28 }} viewport={{ once: true }}><div className="project-content"><div className="project-label"><Cpu size={16} /> Featured project <span>April 2026</span></div><h3>IoT Vehicle<br /><em>Security Framework</em></h3><p>I developed an IoT-based vehicle security system using ESP32 with RFID and fingerprint authentication for secure vehicle access.</p><div className="project-points"><div><strong>Problem</strong><span>Vehicle access needs a more secure, connected layer.</span></div><div><strong>Solution</strong><span>Multi-factor authentication with physical locking and monitoring.</span></div></div><div className="tag-list project-tags">{['ESP32', 'RFID MFRC522', 'Fingerprint Sensor', 'Servo Motor', 'Wi-Fi', 'Arduino IDE', 'Embedded C/C++'].map(t => <span key={t}>{t}</span>)}</div><div className="project-actions"><a className="button button-primary" href="https://github.com/sushil7255" target="_blank" rel="noreferrer">View on GitHub <Code2 size={16} /></a><a className="text-link" href="#project-details">Project details <ArrowUpRight size={15} /></a></div></div><div className="iot-visual" aria-label="Illustration of an IoT vehicle security system"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core"><ScanLine size={34} /><span>ACCESS<br />CONTROL</span></div><div className="node node-a"><Radio size={15} /> RFID</div><div className="node node-b"><ShieldCheck size={15} /> SECURE</div><div className="node node-c"><WifiIcon /> WI-FI</div></div></motion.article><article id="project-details" className="community-card"><div><span className="eyebrow">Community development / June 2026</span><h3>Teaching as a way to keep learning.</h3></div><p>Completed 40 hours of teaching at an educational institute, delivering interactive lessons and supporting students in their learning and academic development. The experience strengthened my communication, leadership, teamwork, mentoring, and time-management skills.</p></article></Section>
    <Section id="Achievements" eyebrow="04 / Milestones" title="Proof of showing up and doing the work."><div className="achievement-grid"><div className="big-achievement"><Trophy size={24} /><strong>1000+</strong><span>programming questions solved on CodeTantra</span></div><div className="achievement-list">{['Attended a workshop on vocabulary development and effective speaking skills.', 'Deployed a project on GitHub and managed its source code and documentation.', 'Earned Warrior, Genie, The Fledgling, Ace and Duelist badges by Infosys Springboard.'].map((a, i) => <div key={i}><BadgeCheck size={18} /><span>{a}</span></div>)}</div></div></Section>
    <Section id="Certifications" eyebrow="05 / Certifications" title="Always learning, always adding context."><div className="cert-grid">{[['Python Bootcamp Certification', 'Infosys Springboard', 'March 2026', <Code2 />], ['Cybersecurity Fundamental Certification', 'Infosys Springboard', 'July 2026', <ShieldCheck />]].map(([title, issuer, date, icon]) => <motion.div className="cert-card" whileHover={{ y: -5 }} key={title as string}><div className="cert-icon">{icon}</div><h3>{title as string}</h3><p>{issuer as string}</p><small>{date as string}</small></motion.div>)}</div></Section>
    <Section id="Education" eyebrow="06 / Education" title="The foundation so far."><div className="education-list">{education.map(([date, school, degree, result], i) => <div className="education-item" key={school}><div className="timeline-dot">{i === 0 ? <GraduationCap size={16} /> : <BookOpen size={15} />}</div><div><span className="date">{date}</span><h3>{school}</h3><p>{degree}</p><strong>{result}</strong></div></div>)}</div></Section>
    <section className="resume-banner"><div><span className="eyebrow">Keep exploring</span><h2>Want to know more about my work and experience?</h2></div><a className="button button-primary" href="/resume/sushil-kumar-rai-cv.pdf" download>Download resume <Download size={16} /></a></section>
    <Section id="Contact" eyebrow="07 / Contact" title="Let's build something together."><div className="contact-card"><p>If you&apos;d like to connect about an opportunity, project, or technical conversation, I&apos;d be happy to hear from you.</p><div className="contact-links"><a href="mailto:sushilkumarrai7255@gmail.com"><Mail /> <span>Email me<small>sushilkumarrai7255@gmail.com</small></span><ArrowUpRight /></a><a href="https://linkedin.com/in/sushilkumarrai7255" target="_blank" rel="noreferrer"><Network /> <span>Connect on LinkedIn<small>sushilkumarrai7255</small></span><ArrowUpRight /></a><a href="https://github.com/sushil7255" target="_blank" rel="noreferrer"><Code2 /> <span>See my GitHub<small>sushil7255</small></span><ArrowUpRight /></a></div></div></Section>
    <footer><span>© 2026 Sushil Kumar Rai</span><span>Built with curiosity and code.</span><a href="#top">Back to top <ArrowUpRight size={14} /></a></footer>
  </main>
}
function WifiIcon() { return <span className="wifi-icon">◌</span> }

